### ISSUE TITLE
Create Store - Status Code 500, 'INTERNAL SERVER ERROR'

### ISSUE THREAD

**Issue by dotnetnoobie** [M4cs/jsonsty#15]
I have been trying to create a store using .NET 5.0 / C# 

I have tried every way I can think of using HttpClient to upload JSON to the API

but I always get a 500 Server error 

This is the JSON I am using to test

```
{"store_name":"MyNewStore","data":{"city":"Sydney","age":99,"name":"Tom"}}
```

**Comment by iamcco** [comment]
Same issue

**Comment by SastaDev** [comment]
Same here....

Also the website https://json.psty.io is down!

**Comment by M4cs** [comment]
Hey all, it seems the server has some issues right now. I've been on a trip away from home so I haven't had access to fix it. Bear with me this might take a week or so, I'm sorry for the down time!

**Comment by M4cs** [comment]
@dotnetnoobie @ShalmonAnandMate @iamcco 

This should be fixed! I got into the server :) Mongo had died for some reason so maybe I have to increase disk space... I might move the server over to a better hosting provider. Please contact me on twitter if you come across more downtime, I will respond much faster! 

https://twitter.com/maxbridgland

or email:

me@maxbridgland.com

**Comment by SastaDev** [comment]
Ah, thanks man!
